apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol01
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: general
  mountOptions:
    - hard
    - intr
  nfs:
    server: 172.28.225.138
    path: /nfs/vol1/pg1
