apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ngx1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ngx1.10.10.20.200.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: ngx1
          servicePort: 80
