apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: volex
  name: volex
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: volex
  template:
    metadata:
      labels:
        run: volex
    spec:
      containers:
      - image: vallard/k8ex7-volume
        imagePullPolicy: Always
        name: volex
        volumeMounts:
          - mountPath: /tmp/projected
            name: volex-vol
          - mountPath: /tmp/projected
            name: volex-secret
      volumes:
      - name: volex-vol
        projected:
          sources:
          - configMap:
              items:
              - key: bgcolor
                path: configmap/bgcolor
              - key: textcolor
                path: configmap/textcolor
              name: volex
          - secret:
              name: volex
              items:
                - key: username
                  path: secrets/username
                - key: password
                  path: secrets/password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: volex
  name: volex
  namespace: default
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    run: volex
  type: LoadBalancer
