apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: volex
  name: volex
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: volex
  template:
    metadata:
      labels:
        run: volex
    spec:
      containers:
      - image: vallard/k8ex7-volume
        imagePullPolicy: Always
        name: volex
        volumeMounts:
          - mountPath: /tmp/projected
            name: volex-vol
      volumes:
      - name: volex-vol
        configMap:
          name: volex
          items:
          - key: bgcolor
            path: configmap/bgcolor
          - key: textcolor
            path: configmap/textcolor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: volex
  name: volex
  namespace: default
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    run: volex
  type: LoadBalancer
